### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by XhmikosR** [goatslacker/fixmyjs.com#10]
Ping @goatslacker

**Comment by leoetlino** [comment]
You can use the following site instead:

https://goatslacker.github.io/fixmyjs.com/

**Comment by XhmikosR** [comment]
Indeed, it seems an issue with the domain. Ping @goatslacker

**Comment by leoetlino** [comment]
The nameservers don't respond for fixmyjs.com.

**Comment by goatslacker** [comment]
fixed
