### ISSUE TITLE
duplicate vars in one line

### ISSUE THREAD

**Issue by simoami** [goatslacker/fixmyjs.com#5]
The following line:

```
  var aw, ah, i, j, c, a, cw, ch, x, w, h, a, col, colWidth, offset, availablePercentWith = viewSize.width,
```

was transformed to:

```
  aw, ah, i, j, c, a, cw, ch, x, w, h, a, col, colWidth, offset, availablePercentWith = viewSize.width,
```

causing all variables to become global. Because "a" is declared twice, it doesn't work well in the context of multiple variables under a single var.

Can you look into this issue?

**Comment by goatslacker** [comment]
Sure, this should be filed here instead: https://github.com/jshint/fixmyjs/issues

**Comment by goatslacker** [comment]
https://github.com/jshint/fixmyjs/issues/57
