### ISSUE TITLE
processing of dot leading decimals doesn't work well.

### ISSUE THREAD

**Issue by simoami** [goatslacker/fixmyjs.com#6]
I got the following line:

```
              var ratio = parseFloat(a.replace('%', ''))*.01;
```

converted to:

```
              var ratio = parseFloat(a0.replace('%', ''))*.01;
```

It seems like it used the first (.) instead of the second one. I'd recommend using a stronger regex pattern for the replacement.

**Comment by goatslacker** [comment]
https://github.com/jshint/fixmyjs/issues/58

**Comment by goatslacker** [comment]
Thanks for reporting!
